server:
  port: 8299
spring:
  datasource:
    url: jdbc:mysql://122.51.69.232:3306/rabbitmq?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1
  rabbitmq:
    host: 122.51.69.232
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  redis:
    host: 122.51.69.232
mybatis-plus:
  mapper-locations: classpath:com/example/send/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
